# Generated by Django 3.0.6 on 2020-05-27 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-pk',)},
        ),
    ]
