# Generated by Django 3.0.6 on 2020-06-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_auto_20200528_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='img',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
